### ISSUE TITLE
Go 버전

### ISSUE THREAD

**Issue by sunho** [wonjinYi/wonjinLab#1]
구글이 만든 Go언어가 세계 최고라는건 모두가 아는 사실입니다. 그런데 지금 이 사이트는 Go버전을 지원하지 않고 있습니다. 공포의 어몽어스 맛을 보기 전에 당장 Go버전을 지원하십시오.

**Comment by wonjinYi** [comment]
좋은 의견 감사합니다. 
@sunho 님이 진행해주시면 성공적인 프로젝트로 발전할 수 있을 것 같습니다.

기대하겠습니다. 53일안에 안나오면 공포의 뿌테 맛을 보게될 수 있으니 주의바랍니다.
